// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJLkpg2Bs6V85ZcgQpBDoIeoHz987Dns0',
    appId: '1:1008363068060:web:393890f23d3c05e91dab59',
    messagingSenderId: '1008363068060',
    projectId: 'firestoretugasfourtwenty',
    authDomain: 'firestoretugasfourtwenty.firebaseapp.com',
    storageBucket: 'firestoretugasfourtwenty.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt2ZAq_-d6zSs4g6ZpVuZrV_OT2ZAwrVw',
    appId: '1:1008363068060:android:de7fc2bda6e911661dab59',
    messagingSenderId: '1008363068060',
    projectId: 'firestoretugasfourtwenty',
    storageBucket: 'firestoretugasfourtwenty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Uj47RLGo0EF2KrZlUxsOVhP4-oJExJo',
    appId: '1:1008363068060:ios:42915004eb1f4c531dab59',
    messagingSenderId: '1008363068060',
    projectId: 'firestoretugasfourtwenty',
    storageBucket: 'firestoretugasfourtwenty.appspot.com',
    iosBundleId: 'com.example.m09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Uj47RLGo0EF2KrZlUxsOVhP4-oJExJo',
    appId: '1:1008363068060:ios:703b1e209675d7ba1dab59',
    messagingSenderId: '1008363068060',
    projectId: 'firestoretugasfourtwenty',
    storageBucket: 'firestoretugasfourtwenty.appspot.com',
    iosBundleId: 'com.example.m09.RunnerTests',
  );
}
